### ISSUE TITLE
Python 3.4 errors

### ISSUE THREAD

**Issue by szepeviktor** [puzzle1536/hubic-wrapper-to-swift#12]
```
# python3.4 ./hubic.py-3 --swift list
-- Access token has expired, try to renew it
Something wrong has happened when refreshing access token
Exception ignored in: <bound method hubic.__del__ of <__main__.hubic object at 0x7ffaa202cef0>>
Traceback (most recent call last):
  File "./hubic.py-3", line 133, in __del__
NameError: name 'open' is not defined


# python3.4 ./hubic.py-3
Exception ignored in: <bound method hubic.__del__ of <__main__.hubic object at 0x7f957d494e80>>
Traceback (most recent call last):
  File "./hubic.py-3", line 104, in __del__
  File "/usr/lib/python3.4/configparser.py", line 931, in remove_section
  File "/usr/lib/python3.4/collections/__init__.py", line 80, in __delitem__
ReferenceError: weakly-referenced object no longer exists
```

**Comment by szepeviktor** [comment]
Do you have 3.4?

**Comment by puzzle1536** [comment]
Hi Viktor,

Sorry, I didn't.
Unfortunately, my debian only has python 3.2.3.
I'll check that with 3.4.

**Comment by puzzle1536** [comment]
Hi Viktor,

Could you check the new hubic.py-3.4 ?
This should fix the issue. I tested it with a ubuntu14.4/python 3.4.0

Unfortunately, it is not compatible with python 3.2

**Comment by szepeviktor** [comment]
Could you write a wrapper to `.json()` and `.json`. It seems only this change is the only difference.

**Comment by szepeviktor** [comment]
BTW I do not see `json()` mentioned: https://docs.python.org/3/whatsnew/3.4.html

**Comment by szepeviktor** [comment]
Could explain why I do not see `.json( ...` in the docs?

**Comment by szepeviktor** [comment]
And **it works** with 3.4.

**Comment by szepeviktor** [comment]
Thank you!

**Comment by puzzle1536** [comment]
@szepeviktor, actually this last json() issue came from "requests" library version.

I tested the script on debian wheezy, which uses python3.2 and and a really old version of requests 0.12.1.
However, before 1.x, json was a property of "requests" and not a callable.
See http://docs.python-requests.org/en/latest/api/#migrating-to-1-x

I will remove this buggy version, and specify in doc, that requests >=1.x is mandatory.

**Comment by szepeviktor** [comment]
[requirements.txt](https://github.com/puzzle1536/hubic-wrapper-to-swift/blob/master/requirements.txt) already says `>=2.0.0`
