### ISSUE TITLE
consider using same config file as the pyrax library

### ISSUE THREAD

**Issue by molobrakos** [puzzle1536/hubic-wrapper-to-swift#14]
I am using duplicity and the pyrax library to make backups to hubic.
Pyrax uses a very similar configuration file ($HOME/.hubic_credentials) as hubic-wrapper-to-swift ($HOME/.hubic.cfg).
Maybe it would be possible to read the hubic credentials from the same file (if it exists), so that the credentials only has to be specified in one place.
The layout of the pyrax hubic config file is documented in: http://duplicity.nongnu.org/duplicity.1.html#sect17
The only difference is that hubic-wrapper-to-swift uses "username" instead of "email".
Also, the hubuc-wrapper-to-swift script rewrites the file and adds its own items. Maybe the credentials could be read from .hubic_credentials and the tokens etc written to .hubic_tokens or something like that?

**Comment by szepeviktor** [comment]
You may add `--config="${HOME}/.hubic_credentials"`
