### ISSUE TITLE
Issue with list

### ISSUE THREAD

**Issue by Issam2204** [puzzle1536/hubic-wrapper-to-swift#15]
Hello!

Thank you very much for this very nice script! It's just what I needed!

I have though an issue when I try the "list" command:

issam@vps162095:~$ python2 ./hubic.py --swift list
OS_STORAGE_URL=https://lb1040.hubic.ovh.net/v1/AUTH_10f925722dd2bce6a5bda3843ac54ca2
OS_AUTH_TOKEN=5523b72629d54ba8ba0a9d38cffe8095
OS_TOKEN_EXPIRE=1429533928.0 (2015-04-20 14:45:28 CEST)
Traceback (most recent call last):
  File "./hubic.py", line 582, in <module>
    hubic.swift(args)
  File "./hubic.py", line 462, in swift
    subprocess.call(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

I've followed your video tutorial but I still don't understand why this happens :|

EDIT: I didn't install python-swiftclient. Such a stupid mistake. Sorry :-)

**Comment by molobrakos** [comment]
You need the swift client installed. 
On Ubuntu: apt-get install python-swiftclient

**Comment by Issam2204** [comment]
Thank you molobrakos :)

I figured it out shortly after.
