### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by Issam2204** [puzzle1536/hubic-wrapper-to-swift#16]
Hello again,

I'm testing hubic-wrapper-to-swift and I tried to send a file of 8GB created with this command:

dd if=/dev/zero of=file10.out bs=1MB count=8000

However, after 13 minutes I received this error:

Object PUT failed: https://lb1040.hubic.ovh.net/v1/AUTH_10f925722dd2bce6a5bda3843ac54ca2/default/home/issam/file10.out 413 Request Entity Too Large  [first 60 chars of response] < html >< h1 >Request Entity Too Large< /h1 >< p >The body of your r

I don't know why. Is it because swift doesn't support files bigger than 5 GB?  Also I found this, but I don't know if it can you to understand this issue: https://bugs.launchpad.net/swift/+bug/1381875

Thank you!

**Comment by molobrakos** [comment]
I believe 5GB is the maximum file size for hubic.
The official documentation mentions 1 GB for the web ui: https://hubic.com/en/limits
This thread mentions 5 GB: http://www.lowendtalk.com/discussion/23140/10-tb-storage-for-10-eur-mo-from-hubic-ovh
