### ISSUE TITLE
hubic.py --swift list gives OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by manu-p** [puzzle1536/hubic-wrapper-to-swift#28]
Hi, after following the instructions [here](https://github.com/puzzle1536/hubic-wrapper-to-swift), I can't make it work:
`manu@8570w:~$ ./Scripts/hubic.py --swift list`
`OS_STORAGE_URL=https://lb1.hubic.ovh.net/v1/AUTH_f793c03f378d4c22b6ccd0b954b99af1`
`OS_AUTH_TOKEN=7cea2c8917b7474d94adcc9ad95e4856`
`OS_TOKEN_EXPIRE=1478453310.0 (2016-11-06 18:28:30 CET)`
`Traceback (most recent call last):`
`  File "./Scripts/hubic.py", line 581, in <module>`
`    hubic.swift(args)`
`  File "./Scripts/hubic.py", line 461, in swift`
`    subprocess.call(cmd)`
`  File "/usr/lib/python2.7/subprocess.py", line 523, in call`
`    return Popen(*popenargs, **kwargs).wait()`
`  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__`
`    errread, errwrite)`
`  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child`
`    raise child_exception`
`OSError: [Errno 2] No such file or directory`

Before that I could do a: 
`manu@8570w:~$ ./Scripts/hubic.py --get /account`
`status : ok`
`firstname : my_firstname`
`language : fr`
`offer : 10240g`
`lastname : my_name`
`activated : True`
`creationDate : 2012-12-04T12:35:55+01:00`
`email : my_mail`

Did I miss something? What can I check to sort it out? Thanks

**Comment by szepeviktor** [comment]
What is the output of `./Scripts/hubic.py --swift -- list` ?

**Comment by manu-p** [comment]
Thanks for the quick reply Viktor, the output's the same : 
`manu@8570w:~/Scripts$ ./hubic.py --swift -- list`
`OS_STORAGE_URL=https://lb1.hubic.ovh.net/v1/AUTH_f793c03f378d4c22b6ccd0b954b99af1`
`OS_AUTH_TOKEN=0d2cc1e7abe3474f877e04eb50c6487b`
`OS_TOKEN_EXPIRE=1478454519.0 (2016-11-06 18:48:39 CET)`
`Traceback (most recent call last):`
`File "./hubic.py", line 581, in <module>`
`hubic.swift(args)`
`File "./hubic.py", line 461, in swift`
`subprocess.call(cmd)`
`File "/usr/lib/python2.7/subprocess.py", line 523, in call`
`return Popen(*popenargs, **kwargs).wait()`
`File "/usr/lib/python2.7/subprocess.py", line 711, in __init__`
`errread, errwrite)`
`File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child`
`raise child_exception`
`OSError: [Errno 2] No such file or directory`

**Comment by szepeviktor** [comment]
Do you have the swift client on your PATH?
Output of `which -a swift`

**Comment by manu-p** [comment]
Nope, no swift in the PATH.

And when I type `swift` on the command line, I'm told something like "swift" program may be found in in the following packages : 
- python-swiftclient
- python3-swiftclient
  Try : `sudo apt install <selected package>`

So I just installed python-swiftclient and... it's working fine now. 
I'm on 16.04, and maybe it should be mentioned in the [Requirements](https://github.com/puzzle1536/hubic-wrapper-to-swift#requirements) :  "The following packages should be enough to make it work on Ubuntu `apt-get install python-swift python-swiftclient python-requests`.

Thank you Viktor !

**Comment by szepeviktor** [comment]
See the readme

> The following packages should be enough to make it work on Ubuntu 14.04 apt-get install python-swift python-requests or using pip pip install -r requirements.txt

**Comment by szepeviktor** [comment]
python-swiftclient is a dependency of python-swift

**Comment by szepeviktor** [comment]
You're right, not in modern Debian (after current stable)
